In [1]:
class Quest:
    def __init__(self, q, a):
        self.q = q
        self.a = a


que = [
    "1) Speed of sound is?\n a) 500m/s\n b) 300m/s\n c) 342m/s\n d) 800m/s\n",
    "2) Speed of sound is?\n a) 500m/s\n b) 300m/s\n c) 342m/s\n d) 800m/s\n",
    "3) Speed of sound is?\n a) 500m/s\n b) 300m/s\n c) 342m/s\n d) 800m/s\n",
    "4) Speed of sound is?\n a) 500m/s\n b) 300m/s\n c) 342m/s\n d) 800m/s\n",
    "5) Speed of sound is?\n a) 500m/s\n b) 300m/s\n c) 342m/s\n d) 800m/s\n"
]

ans = [
    Quest(que[0], "c"),
    Quest(que[1], "a"),
    Quest(que[2], "b"),
    Quest(que[3], "c"),
    Quest(que[4], "a")
]

score = 0

for i in ans:
    answer = input(i.q)

    if answer == i.a:
        score = score + 1

print("Total score:", score)

Total score: 1


In [3]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age  = age

        def Myfunc(self):
            print("my Name is"+self.name)

p1 = Person("Siya",34)

print(p1)

del p1



In [4]:
class MyClass:
    x = 26

p1 = MyClass()
p2 = MyClass()
p3 = MyClass()

print(p1.x)
print(p2.x)
print(p3.x)

26
26
26


In [5]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age  = age

p1 = Person("soumya",56)

print(p1.name)
print(p1.age)
        

soumya
56


In [1]:
set1 = {"siya","Arpita","shreya"}
set2 = {"Nitya","choti","chirag"}
set3 = {"rudra","pratik","pawan"}
set4 = {1,2,3,4,5,6}

set5 = set1|set2|set3|set4

print(set5)

{1, 2, 3, 4, 'pratik', 5, 6, 'Arpita', 'rudra', 'Nitya', 'chirag', 'pawan', 'choti', 'siya', 'shreya'}


In [2]:
set1 = {"siya","Arpita","shreya"}
set2 = {"Nitya","choti","chirag"}
set3 = {"rudra","pratik","pawan"}
set4 = {1,2,3,4,5,6}

set5=set5.union(set1,set2,set3,set4)

print(set5)

{1, 2, 3, 4, 'pratik', 5, 6, 'rudra', 'Nitya', 'pawan', 'siya', 'Arpita', 'chirag', 'choti', 'shreya'}


In [3]:
set1 = {"siya","Arpita","shreya"}
set2 = {"Nitya","choti","shreya"}

set3 = set1&set2

print(set3)


{'shreya'}


In [4]:
set1 = {"siya","Arpita","shreya"}
set2 = {"Nitya","choti","shreya"}

set3 = set1^set2

print(set3)

{'Arpita', 'Nitya', 'choti', 'siya'}


In [4]:
# Colorful Personal Introduction Program

from colorama import Fore, Style, init

init(autoreset=True)

print(Fore.CYAN + "=" * 50)
print(Fore.YELLOW + "           🌟 MY INTRODUCTION 🌟")
print(Fore.CYAN + "=" * 50)

print(Fore.GREEN + "👩 Name       : " + Fore.WHITE + "Siya Singh")
print(Fore.BLUE + "🎓 Course     : " + Fore.WHITE + "B.Tech CSE (AI & ML)")
print(Fore.MAGENTA + "💻 Interest   : " + Fore.WHITE + "Backend Development, Database, AI & ML")
print(Fore.RED + "🎯 Goal       : " + Fore.WHITE + "To become a successful Data/AI professional")
print(Fore.YELLOW + "🎵 Hobby      : " + Fore.WHITE + "Singing, Dancing & Photography")

print(Fore.CYAN + "\n" + "-" * 50)

print(Fore.GREEN + "✨ About Me:")
print(Fore.WHITE + "I am a passionate and hardworking student.")
print(Fore.WHITE + "I love learning new technologies and improving my skills.")
print(Fore.WHITE + "I believe in consistency, discipline and continuous growth.")
print(Fore.WHITE + "My goal is to build a successful career in technology.")

print(Fore.CYAN + "-" * 50)
print(Fore.YELLOW + "        🚀 KEEP LEARNING, KEEP GROWING! 🚀")
print(Fore.CYAN + "=" * 50)

           🌟 MY INTRODUCTION 🌟
👩 Name       : Siya Singh
🎓 Course     : B.Tech CSE (AI & ML)
💻 Interest   : Backend Development, Database, AI & ML
🎯 Goal       : To become a successful Data/AI professional
🎵 Hobby      : Singing, Dancing & Photography

--------------------------------------------------
✨ About Me:
I am a passionate and hardworking student.
I love learning new technologies and improving my skills.
I believe in consistency, discipline and continuous growth.
My goal is to build a successful career in technology.
--------------------------------------------------
        🚀 KEEP LEARNING, KEEP GROWING! 🚀


In [1]:
import numpy as np

In [ ]:
ar = np.array([1,2,3,4,5,6])
print(ar)

[1 2 3 4 5 6]


In [ ]:
# // array should be of single datatype

In [4]:
print(type(ar))

<class 'numpy.ndarray'>


In [5]:
ar.dtype

dtype('int64')

In [6]:
ar.ndim

1

In [7]:
ar.size

6

In [10]:
ar.sum()

np.int64(21)

In [11]:
ar.shape

(6,)

In [ ]:
# ar.reshape(4,3)
# ar.reshape(-1,12)
# i have not mentioning the no. of row instead of that i have mentioning the -1

In [12]:
arr = np.array([[1,2,3,4,8,9],[5,6,7,8,1,9]])

demo = arr.reshape(3,4)

demo

array([[1, 2, 3, 4],
       [8, 9, 5, 6],
       [7, 8, 1, 9]])

In [21]:
d = np.array([1,2,3,4,5,6,7,8])
d.reshape(2,2,2)


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
d.std()

np.float64(2.8722813232690143)

In [23]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
d.var()

np.float64(8.25)

In [25]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
k=np.eye(3)
k

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
d = np.array([1,2,3,4,5,6,7,8,9,10])
k=np.zeros(3)
k

array([0., 0., 0.])

In [30]:
d = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
k=d.reshape(3,4).copy()
d[0] =100
k.sum()

np.int64(78)

In [31]:
k.sum(axis=0)

array([15, 18, 21, 24])

In [32]:
k.sum(axis=1)

array([10, 26, 42])

In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,8,9],[5,6,7,8,1,9]])
demo = arr.reshape(3,4)
demo=demo.ravel()
demo[0] =100
demo
print(arr)

# it shows linking from main arr means arr.ravel performs operation on the same index

[[100   2   3   4   8   9]
 [  5   6   7   8   1   9]]


In [ ]:

import numpy as np
arr = np.array([[1,2,3,4,8,9],[5,6,7,8,1,9]])
demo = arr.reshape(3,4)
demo=demo.flatten()
demo[0] =100
demo
print(arr)
# it creates a copy and performs the required operation on that only

[[1 2 3 4 8 9]
 [5 6 7 8 1 9]]


In [9]:
mk = (demo>50) & (demo>70) 
mk

array([ True, False, False, False, False, False, False, False, False,
       False, False, False])

In [11]:
# t means transpose
arr.transpose()

array([[100,   5],
       [  2,   6],
       [  3,   7],
       [  4,   8],
       [  8,   1],
       [  9,   9]])

In [1]:
import numpy as np

In [5]:
d = np.array([100,23,34,56,78,98,90,12,78])
print(d%10)

[0 3 4 6 8 8 0 2 8]


In [ ]:
n = [5,6,9]
print(n*3) #broadcasting

[5, 6, 9, 5, 6, 9, 5, 6, 9]


In [ ]:
d = np.array([100,23,34,56,78,98,90,12,78,80])
mask =(d>=80)
print(d[mask])

print(d[~mask])

[100  98  90  80]
[23 34 56 78 12 78]


In [14]:
d = np.array([100,23,34,56,78,98,90,12,78,80])
mask =((d>70) & (d<90))
print(d[mask])

[78 78 80]


In [35]:

# print(np.where(k%2==0,"Even","odd")) 
# // it return the true condition indexes
print(np.select([k%2==0],["Even"],default="odd"))

[['odd' 'Even' 'odd' 'Even']
 ['odd' 'Even' 'odd' 'Even']
 ['odd' 'Even' 'odd' 'Even']]


In [39]:
cond = [((d>=40)&(d<=75)),((d>75)&(d<=100))]
choice = ["small","medium"]
np.select(cond,choice,default="Large")

array(['medium', 'Large', 'Large', 'Large', 'Large', 'Large', 'Large',
       'Large', 'Large', 'Large', 'Large', 'Large'], dtype='<U6')

In [38]:
m = np.array([78,89,90,67,56,70,45,100,89,65,95,91,94,86,82,81,70,50,40,30])
print(np.select([m>=90,m>=70,m>=50,m>=33,m<33],["A","B","C","D","Fail"],default="Fail"))

['B' 'B' 'A' 'C' 'C' 'B' 'D' 'A' 'B' 'C' 'A' 'A' 'A' 'B' 'B' 'B' 'B' 'C'
 'D' 'Fail']
