In [1]:
import numpy as np

In [3]:
lst = [1,2,3,4]
arr = np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr.shape

(4,)

In [9]:
lst1 = [1,2,3,4,5]
lst2 = [2,3,4,5,6]
lst3 = [3,4,5,6,7]
arr1=np.array([lst1,lst2,lst3])
arr1


array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [10]:
arr1.shape

(3, 5)

In [11]:
arr

array([1, 2, 3, 4])

In [12]:
arr[3]

np.int64(4)

In [13]:
arr[3]=11

In [14]:
arr

array([ 1,  2,  3, 11])

In [15]:
arr[1:3]

array([2, 3])

In [16]:
arr[:-1]

array([1, 2, 3])

In [17]:
arr[-1]

np.int64(11)

In [18]:
arr[::]

array([ 1,  2,  3, 11])

In [19]:
arr[::-1]

array([11,  3,  2,  1])

In [20]:
arr[::-2]

array([11,  2])

In [21]:
arr1

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [22]:
arr1[:,1]

array([2, 3, 4])

In [23]:
arr1[1:,1:3]

array([[3, 4],
       [4, 5]])

In [24]:
arr1[1:,3:]

array([[5, 6],
       [6, 7]])

In [27]:
arr1[0:2,1:4]

array([[2, 3, 4],
       [3, 4, 5]])

In [29]:
arr1[0:,3:].shape

(3, 2)

In [31]:
arr[arr<2]

array([1])

In [32]:
arr1.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 3, 4],
       [5, 6, 7]])

In [39]:
np.arange(1,20,2).reshape(2,5,1)

array([[[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9]],

       [[11],
        [13],
        [15],
        [17],
        [19]]])

In [41]:
np.ones((5,1))

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [42]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
np.random.randint(10,50,4).reshape(2,2)

array([[42, 13],
       [42, 17]], dtype=int32)

In [44]:
np.random.randn(5,6)

array([[ 1.01978264,  0.46966857, -0.75198705, -0.59261435,  0.45752612,
         0.56507803],
       [-0.71012971, -0.70655774,  2.6967898 , -1.37453358, -0.61030561,
        -0.22630549],
       [ 0.67995944, -0.17516437,  0.31406911,  1.11381501,  1.21165947,
         0.72392302],
       [-0.0537137 ,  0.63882819, -0.12469439,  1.27589947,  0.45681659,
        -1.13939327],
       [-0.33288173,  0.59181694, -0.69227298,  0.57139173, -0.90500924,
        -1.37505173]])

In [45]:
np.random.random_sample((4,7))

array([[0.54020284, 0.29154508, 0.85607296, 0.18837774, 0.12356477,
        0.9215272 , 0.79172435],
       [0.38296147, 0.85943575, 0.92136165, 0.4709228 , 0.83002201,
        0.54402029, 0.75179063],
       [0.55741324, 0.09386349, 0.96590391, 0.15857191, 0.60726756,
        0.44001708, 0.00442116],
       [0.70897354, 0.3348241 , 0.01199547, 0.85638376, 0.19008325,
        0.22407278, 0.50817308]])